### ISSUE TITLE
Comments not displayed

### ISSUE THREAD

**Issue by chut211** [ChessCorp/chess-club-ui#19]
Connected, after ending a game against IA, when a comment is posted 
then 
the comment is not displayed. It's only displayed:
[object Object]

![image](https://cloud.githubusercontent.com/assets/15700287/12099907/c7ffd9ac-b32b-11e5-86b2-dbea5c6b7d4b.png)

**Comment by chut211** [comment]
Same as #8 ?

**Comment by alcibiade** [comment]
Yes, the comments system is not operational yet, that's why #8 is still open, but let this one open, I'll close them both when comments are available.
