### ISSUE TITLE
My games not stored

### ISSUE THREAD

**Issue by chut211** [ChessCorp/chess-club-ui#20]
Once connected, games already played are not stored.

In this example, some lines are expected in the "Games" section.
![image](https://cloud.githubusercontent.com/assets/15700287/12100486/8beed6bc-b32f-11e5-8d55-0fcd16bacbb1.png)

**Comment by alcibiade** [comment]
Do you see them in "Your profile" ?

**Comment by alcibiade** [comment]
Because now I filter to display only open games since the 0.4.0 update. This means that currently you can't see closed games until I add an archive section in the player profile page.

**Comment by chut211** [comment]
No games in "Your profile" section.
![image](https://cloud.githubusercontent.com/assets/15700287/12100617/62bfea14-b330-11e5-8b9e-aa8035876409.png)

**Comment by alcibiade** [comment]
So it's not an issue. Just open another ticket to add the games history in the profile. It's planned but it's always good to have a ticket.

**Comment by chut211** [comment]
"Current games" should be better directly for the section title, don't you think ? 
I think History and current games could be expected by users in "Games"

**Comment by alcibiade** [comment]
Yes but this should be available not only for the authenticated user but for any user profile so that you can search/browse player history. We'll see that once the feature is added in the profile.

Maybe we could add a Search menu item that would display a generic search page.
