### ISSUE TITLE
Login window shadow

### ISSUE THREAD

**Issue by alexbagirov** [ChessCorp/chess-club-ui#22]
When I am trying to log in, I usually see this.
![chesscorp](https://cloud.githubusercontent.com/assets/6885864/12170604/9baf5202-b564-11e5-9b69-c9748c274c5f.jpg)

The window becomes dark and I can't enter or push anything. But it works well after reload. I use the latest Chrome on Windows 10 (the same for Android).

**Comment by alcibiade** [comment]
Yes this is the same as #15. It happens as soon as you scroll vertically at least once...

I have a workaround solution for this coming from Google but didn't implement it yet. For now, simply refresh your browser.

**Comment by alcibiade** [comment]
Duplicate of #15

**Comment by alexbagirov** [comment]
Fine, so I'm going to close it right now.
