### ISSUE TITLE
Signup dialogs broken on game screen

### ISSUE THREAD

**Issue by alcibiade** [ChessCorp/chess-club-ui#5]
When opening dialogs over a board component, the display is completely messed up:

![dialogoverboard](https://cloud.githubusercontent.com/assets/3389277/10432764/c0cd6574-710d-11e5-9df4-f0b233bc25fa.png)

**Comment by alexbagirov** [comment]
Where is that demo located?

**Comment by alcibiade** [comment]
It's still far from being playable but advancing a bit more every day :-)

I usually host the latest version on my raspberry at http://alcibiade.duckdns.org/

**Comment by alcibiade** [comment]
Now I have setup a permanent Amazon Web Services at http://chesscorp.org/
