### ISSUE TITLE
Support markdown syntax in comments

### ISSUE THREAD

**Issue by alcibiade** [ChessCorp/chess-club-ui#8]
Comments are currently raw texts, we should support markdown to allow rich presentation.

**Comment by cyChop** [comment]
### Java Markdown processors as [listed by the W3c](http://www.w3.org/community/markdown/wiki/MarkdownImplementations):

* [MarkdownJ](https://github.com/myabc/markdownj)
* [pegdown](https://github.com/sirthias/pegdown/)
* [MarkdownPapers](http://markdown.tautua.org/)
* [Txtmark](https://github.com/rjeschke/txtmark)

### JavaScript processors (short selection from the same source)

* [markdown-js](https://github.com/evilstreak/markdown-js)
* [marked](https://github.com/chjj/marked)
* [text.js](https://github.com/sheremetyev/texts.js)

**Comment by alcibiade** [comment]
Just found a polymer component that renders markdown directly: https://github.com/robdodson/mark-down
